name: skip-unit ci

on:
  push:
    branches: '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron:  '0 10,20 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  ci:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: swift build
      - name: Test
        run: swift test
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          MODULE="SkipUnit"
          PACKAGE="skip-unit"
          TAG="${GITHUB_REF#refs/tags/}"

          gradle assemble --project-dir Packages/Skip/${PACKAGE}/${MODULE}KtTests/skip-transpiler -PbuildDir=.build/${MODULE}

          echo "Creating release: ${TAG}"
          mkdir -p Packages/Skip/artifacts/
          PKGDIR="../../../../../../Packages/Skip/artifacts/"

          # copy the built release .aar
          cd ./.build/plugins/outputs/${PACKAGE}/${MODULE}KtTests/skip-transpiler
          cp -a ${MODULE}/.build/${MODULE}/outputs/aar/${MODULE}-release.aar ${PKGDIR}/${PACKAGE}-${TAG}.aar
          zip -r ${PKGDIR}/${PACKAGE}-${TAG}-sources.zip . -x '.*' -x '.*/*' -x '*/.*/*'

          cd ${PKGDIR}

          shasum -a 256 *.* > checksums.txt

          cat > relnotes.md << EOF
          These are the checksums for the release artifacts:
          EOF

          echo '```' >> relnotes.md
          cat checksums.txt >> relnotes.md
          echo '```' >> relnotes.md

          gh release create "${TAG}" --title "Release ${TAG}" -F relnotes.md
          rm relnotes.md
          gh release upload "${TAG}" -- *.*

