name: skip-unit ci

on:
  push:
    branches: '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron:  '0 10,20 * * *'
  workflow_dispatch:
  pull_request:

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  ci:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: swift test
      - name: Assemble
        run: |
          gradle assemble --project-dir Packages/Skip/skip-unit/SkipUnitKtTests/skip-transpiler -PbuildDir=.build/SkipUnit

      - name: "Create Release"
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          echo "Creating release: ${TAG}"

          mkdir -p Packages/Skip/artifacts/
          cp -a ./.build/plugins/outputs/skip-unit/SkipUnitKtTests/skip-transpiler/SkipUnit/.build/SkipUnit/outputs/aar/SkipUnit-release.aar Packages/Skip/artifacts/skip-unit-${TAG}.aar

          cd Packages/Skip/artifacts/

          shasum -a 256 *.* > checksums.txt

          cat > relnotes.md << EOF
          These are the checksums for the release artifacts:
          EOF

          echo '```' >> relnotes.md
          cat checksums.txt >> relnotes.md
          echo '```' >> relnotes.md

          gh release create "${TAG}" --title "Release ${TAG}" -F relnotes.md
          rm relnotes.md
          gh release upload "${TAG}" -- *.*

